input:
  class_0: 
    QCD15to7000:
      path:  'QCD_15to7000'
      files: 'output_[1-10].root' 
      xs:   1.0
      model_param: 
        mZ:    null
      force_xs: false 
      isMC:     true 
      maxevents_scale: 1.0
  class_1:
    ZtoQQMLM250:
      path: 'ztoqq_mlm_250'
      files: 'output_*.root'
      xs: 1.0
      model_param:
        mZ: 250.0
      force_xs: false
      isMC: true
      maxevents_scale: 1.0
  #class_1:
  #  QCD15to7000:
  #    path:  'QCD_15to7000'
  #    files: 'output_[5-8].root' 
  #    xs:   1.0
  #    model_param: 
  #      mpi:    null 
  #      mA:     null 
  #      ctau:   null 
  #    force_xs: false 
  #    isMC:     true 
  #    maxevents_scale: 1.0
    
    
