# ========================================================================
## Raytune setup
# ========================================================================

param:
  
  #active:         ['xgb1']
  active:  [null]
  num_samples:    1000  # Trial count parameter

setup:

  xgb_trial_0:
    search_algo: 'HyperOpt'

    search_metric:
      metric: 'AUC'
      mode: 'max'

    param:
      
      num_boost_round:
        type: "tune.randint(20, 400)"