# L1DS tune0.yml

rootname: 'l1ds'
rngseed: 123456                       # Fixed seed for training data mixing
num_cpus: 1                           # 0 for automatic
inputvars: 'mvavars'                  # Main file input description python file

# ----------------------------------------------------
mva_param: &MVA_INPUT_PARAM
  use_conditional: false              # Conditional (theory parametric) input

  primary_classes: [0,1]              # Primary class IDs in MVA (train, ROC etc.)
  signal_class: 1                     # Signal class ID
  DA_class:    -2                     # Domain Adaptation class
  
  inputvar_scalar: 'MVA_SCALAR_VARS'  # Input variables, implemented under mvavars.py
  inputvar_jagged: 'MVA_JAGGED_VARS'
  
  # For xgboost etc. fixed input dimension models
  # The variable names below need to match the nanoAOD variable names, e.g. 'Jet_*'
  jagged_maxdim:
    
    Jet:  4

  # Filtering of collection entries (for BDT)
  jagged_filter:
    
    - name: 'Jet'
      condition: 'Jet.pt > 0'

  frac: [0.6, 0.1, 0.3]  

  # Variable imputation
  imputation_param:
    active: true                     # True / False
    var: null                        # Array of variables to be imputated, if null, then all
    algorithm: 'constant'            # Algorithm type: 'constant', iterative' (vector), knn' (vector), 'mean' (scalar), 'median' (scalar)
    fill_value: -999.0               # For constant imputation
    knn_k: 8                         # Number of nearest neighbours considered
    values: null 
  
  varnorm: null                     # Variable normalization, null for no normalization

# ----------------------------------------------------
genesis_runmode:

  maxevents: null
  inputmap: 'mc_input.yml'
  tree_name: null

  filterfunc: 'filter_nofilter'
  cutfunc: 'cut_fiducial'
  targetfunc: null

  xcorr_flow: False
  pickle_size: 100000

# ----------------------------------------------------
plot_param: !include configs/l1ds/plot_param.yml
