basic:
  active: True
  nbins:  70
  percentile_range: [0.5, 99.5]
  exclude_vals: [null, 0]
  plot_unweighted: True

corrmat:
  active: false

contours: 
  active: false

MVA_output:
  active: true
  edges: 80

ROC:
  active: true
  num_bootstrap: 200
  xmin: 1.0E-4

ROC_binned:
  active: false
  num_bootstrap: 200
  xmin: 1.0E-4
  
MVA_2D:
  active: false
