input:
  class_0: 
    QCD15to7000:
      path:  'QCD_15to7000_withtowers'
      files: 'nano_[1-20].root' 
      xs:   1.0
      model_param: 
        mZ:    null
      force_xs: false 
      isMC:     true 
      maxevents_scale: 1.0
  class_1:
    suep:
      path: 'ordered_suep'
      files: 'nano_[1-20].root'
      xs: 1.0
      model_param:
        mZ: null
      force_xs: false
      isMC: true
      maxevents_scale: 1.0

    
